name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up CMake 3.20
        uses: Kitware/setup-cmake@v1
        with:
          cmake-version: 3.20
      - name: Create build directory
        run: mkdir build
      - name: Configure build
        run: cmake -B build
      - name: Build project
        run: cmake --build build
      - name: Move executable to out directory
        run: mv build/my_executable out/
  push_out_directory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push Out Directory to Master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update out directory"
          git push