name: Build on MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job1:
      build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: master
        - name: Get CMake
          uses: symbitic/install-cmake@master
        - name: build
          run: |
            mkdir build
            cd ./build
            cmake ..
            make
  job2:
    build:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: master
        - name: Get CMake
          uses: symbitic/install-cmake@master
        - name: build
          run: |
            mkdir build
            cd ./build
            cmake .. -G "MinGW Makefiles"
            cmake --build .
  job3:
    build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v2
          with:
            ref: master
        - name: Get CMake
          uses: symbitic/install-cmake@master
        - name: build
          run: |
            mkdir build
            cd ./build
            cmake ..
            make         