name: Build on MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Get CMake
        uses: symbitic/install-cmake@master
      - name: build
        run: |
          mkdir build
          cd ./build
          cmake ..
          make         