name: Build and Push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Install CMake 3.20
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake
      - name: Create build directory
        run: mkdir build
      - name: Configure build
        run: cmake -B build
      - name: Build project
        run: cmake --build build
      - name: Move executable to out directory
        run: mv build/my_executable out/
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Update out directory
          add: out
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
